version: "3.8"
services:
  backend-trains:
    image: backend-trains
    build:
      context: ./DotNET_ASP_App
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
      - mqtt5
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"  # for TCP
    #     - "9001:9001"  # for WebSockets (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw  # Mount the custom config directory
      - data:/mosquitto/data:rw
      - log:/mosquitto/log:rw
    command: >
      sh -c "
      touch /mosquitto/config/pwfile &&
      mosquitto_passwd -b /mosquitto/config/pwfile user1 password1 &&
      mosquitto_passwd -b /mosquitto/config/pwfile user2 password2 &&
      mosquitto -c /mosquitto/config/mosquitto.conf
      "
    restart: unless-stopped

  frontend-trains:
      build:
        context: ./frontend-trains
        dockerfile: Dockerfile
      ports:
        - "8147:8147"
      volumes:
        - ./frontend-trains:/app
        - /app/node_modules
      stdin_open: true
      tty: true
      environment:
        - PORT=8147
        - BROWSER=none
        - CI=true
      depends_on:
        - backend-trains
      command: npm start

volumes:
  mongodata:
    driver: local
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network
